id: I5A46D087
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:40:51.484060+00:00
last_modified: 2022-12-15 07:40:51.484074+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-066-003
  title: Toh_245-The_Sections_of_Dharma-v2
bases:
  B3B4:
    source_metadata: null
    order: 1
    base_file: B3B4.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
